# Generated by Django 4.1 on 2022-10-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='用例名称')),
                ('hoster_name', models.CharField(max_length=60, verbose_name='作者名称')),
                ('publish', models.BooleanField(verbose_name='用例是否发布')),
                ('api_id', models.CharField(max_length=60, verbose_name='用例名称')),
                ('annotation', models.CharField(max_length=60, verbose_name='用例注释')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=60, verbose_name='域名')),
                ('name', models.CharField(max_length=60, verbose_name='域名服务名称')),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='接口名称')),
                ('hoster_name', models.CharField(max_length=60, verbose_name='作者名称')),
                ('headers', models.CharField(max_length=60, verbose_name='请求头')),
                ('method', models.CharField(max_length=60, verbose_name='请求方式')),
                ('body', models.CharField(max_length=60, verbose_name='请求体')),
                ('annotation', models.CharField(max_length=60, verbose_name='接口注释')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.case')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.url')),
            ],
        ),
    ]
