# Generated by Django 4.1 on 2025-04-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='api',
            name='case',
        ),
        migrations.AddField(
            model_name='api',
            name='desc',
            field=models.CharField(max_length=60, null=True, verbose_name='接口注释'),
        ),
        migrations.AddField(
            model_name='api',
            name='publish',
            field=models.BooleanField(null=True, verbose_name='接口是否发布'),
        ),
    ]
