# Generated by Django 5.2.15 on 2026-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用例ID')),
                ('name', models.CharField(max_length=60, verbose_name='用例名称')),
                ('hoster_name', models.CharField(max_length=60, verbose_name='作者名称')),
                ('case_models', models.JSONField(blank=True, default=list, null=True, verbose_name='用例步骤')),
                ('case_tag', models.CharField(max_length=60, null=True, verbose_name='用例标签')),
                ('annotation', models.CharField(max_length=60, verbose_name='用例注释')),
                ('case_setup', models.CharField(max_length=60, null=True, verbose_name='用例前置条件')),
                ('case_teardown', models.CharField(max_length=60, null=True, verbose_name='用例后置条件')),
                ('case_steps', models.JSONField(blank=True, default=list, null=True, verbose_name='用例步骤')),
                ('case_asserts', models.JSONField(blank=True, default=list, null=True, verbose_name='用例断言')),
                ('exec_status', models.JSONField(blank=True, default=dict, null=True, verbose_name='用例执行状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_person', models.CharField(max_length=60, verbose_name='最后更新人')),
            ],
        ),
    ]
